[editor]
showgrid = false
showcrosshairs = false
showrulers = true
showcursors = true
snaptogrid = false
snapnear = true
showwireframe = false
recent = ["C:\\Users\\mcclu\\Projects\\feathergui\\media\\editor\\editor - Copy.xml", "C:\\Users\\mcclu\\Projects\\feathergui\\media\\editor\\editor.out.xml"]

