[editor]
showgrid = false
showcrosshairs = false
showrulers = true
showcursors = true
snaptogrid = false
snapnear = true
showwireframe = false
recent = ["D:\\Erik Documents\\Visual Studio 2017\\Projects\\feathergui\\media\\editor\\editor.xml", "D:\\Erik Documents\\Visual Studio 2017\\Projects\\feathergui\\media\\editor\\editor.out.xml"]

